baseURL = "https://daegwan00.github.io/"
languageCode = "ko-KR"
title = "ACK"
theme = "Book"

[params]
  BookTheme = "auto"
  BookToC = true
  BookSearch = true
  BookComments = false
  BookMenuBundle = false

[taxonomies]
  category = "categories"
  tag = "tags"
